version: "3"

services:
  web:
    depends_on:
      - db
    build: ./node
    restart: always
    ports:
      - 3030:3000
    volumes:
      - ./app:/home/node/app
    command: npm start
    hostname: node01
    domainname: example.local
  db:
    build: ./mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    hostname: mongo01
    domainname: example.local 
